# Name of the project
PROJECT_NAME = Empolyee_Managements

#Doxyfile folder
DOC = documentation

#All source code files
SRC = Empolyee.c\
src/Empolyee_operations.c

#All test source files
TEST_SRC = src/Empolyee_operations.c\

TEST_OUTPUT = Test_e.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = emp.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html


Build:
	gcc main.c Empolyee_operation.c 

Run:
	./e.out